//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotosMissTeen_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelVotosContainer : DbContext
    {
        public ModelVotosContainer()
            : base("name=ModelVotosContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fase> Fases { get; set; }
        public virtual DbSet<Votos> Votos { get; set; }
        public virtual DbSet<Jurado> Jurados { get; set; }
        public virtual DbSet<Participante> Participantes { get; set; }
    }
}
