//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotosMissTeen_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votos
    {
        public int Id { get; set; }
        public double Puntuacion { get; set; }
        public int JuradoId { get; set; }
        public int FaseId { get; set; }
        public int ParticipanteId { get; set; }
    
        public virtual Jurado Jurado { get; set; }
        public virtual Fase Fase { get; set; }
        public virtual Participante Participante { get; set; }
    }
}
